load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "nanobench",
    visibility = ["//visibility:public"],
    srcs = [
        "nanobench.cpp",
    ],
    deps = [
        "@com_github_martinus_nanobench//:libnanobench",
    ],
)
